spring:
    application:
        name: gingflix

    datasource:
        url: jdbc:postgresql://localhost:5434/clean
        username: peuser
        password: rhtmxm

    jpa:
        hibernate:
            ddl-auto: validate
        show-sql: false
        properties:
            hibernate:
                format_sql: true
                highlight_sql: true

    graphql:
        graphiql:
            enabled: true

    servlet:
        multipart:
            max-file-size: 10GB
            max-request-size: 10GB

logging:
    level:
        # SQL 출력(hibernate)
        org.hibernate.SQL: debug
        # 바인딩 파라미터까지 보고 싶으면 trace로
        org.hibernate.orm.jdbc.bind: trace
        # (선택) 트랜잭션 로그
        org.springframework.transaction: info

jwt:
    secret: "ioUK3eJ4g40BOEqS9wdiKc2OwgLz3Uzm+EXO+L50YnE="
    expiration-ms: 36000000 # Access  token 만료: 10시간
    refresh-expiration-ms: 604800000 # Refresh token 만료: 7일

app:
    upload:
        base-dir: uploads
    cors:
        allowed-origins:
            - "http://localhost:5173"
            - "http://127.0.0.1:5173"
        allowed-methods: ["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"]
        allowed-headers: ["Authorization", "Content-Type", "X-CSRF-Token"]
        exposed-headers: ["Set-Cookie"]
        allow-credentials: true
        max-age: 3600
